pipeline {
    agent any

    stages {

        stage('Clean Build Environment') {
            steps {
                dir('aceest') {
                    sh '''
                        rm -rf venv
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Lint') {
            steps {
                dir('aceest') {
                    sh '''
                        . venv/bin/activate
                        python -m py_compile app.py
                    '''
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('aceest') {
                    sh '''
                        . venv/bin/activate
                        pytest
                    '''
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('aceest') {
                    sh '''
                        docker build -t aceest-fitness:latest .
                    '''
                }
            }
        }

        stage('Test in Container') {
            steps {
                dir('aceest') {
                    sh '''
                        docker run --rm aceest-fitness:latest pytest
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'BUILD SUCCESSFUL'
        }

        failure {
            echo 'BUILD FAILED'
        }
    }
}
